import type { Product } from "@/@types";
import {v4 as uuidv4} from 'uuid'

export const productsData: Product[] = [
  {
    id: uuidv4(),
    title: 'Lavadora De Alta Pressão Kärcher',
    description: 'A Lavadora de Alta Pressão Kärcher Compacta é prática e eficiente para limpezas do dia a dia',
    image: '/products/P-001.webp',
    link: 'https://mercadolivre.com/sec/1XYVQ7h',
  },
  {
    id: uuidv4(),
    title: 'Notebook Pro',
    description: 'Um notebook potente para trabalho e entretenimento.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/notebook-pro',
  },
  {
    id: uuidv4(),
    title: 'Fones de Ouvido Bluetooth',
    description: 'Fones de ouvido sem fio com cancelamento de ruído.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/fones-bluetooth',
  },
  {
    id: uuidv4(),
    title: 'Smartwatch Sport',
    description: 'Um smartwatch para monitorar sua saúde e atividades físicas.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/smartwatch-sport',
  },
  {
    id: uuidv4(),
    title: 'Câmera Mirrorless',
    description: 'Uma câmera para fotógrafos profissionais e amadores.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/camera-mirrorless',
  },
  {
    id: uuidv4(),
    title: 'Tablet Ultra',
    description: 'Um tablet fino e leve para leitura e navegação na web.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/tablet-ultra',
  },
  {
    id: uuidv4(),
    title: 'Console de Jogos NextGen',
    description: 'Um console de jogos com gráficos de última geração.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/console-nextgen',
  },
  {
    id: uuidv4(),
    title: 'Impressora Multifuncional',
    description: 'Uma impressora para imprimir, digitalizar e copiar documentos.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/impressora-multifuncional',
  },
  {
    id: uuidv4(),
    title: 'Monitor 4K',
    description: 'Um monitor com alta resolução para edição de vídeo e jogos.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/monitor-4k',
  },
  {
    id: uuidv4(),
    title: 'Teclado Mecânico',
    description: 'Um teclado para digitar com precisão e conforto.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/teclado-mecanico',
  },
  {
    id: uuidv4(),
    title: 'Mouse Gamer',
    description: 'Um mouse com alta sensibilidade para jogos competitivos.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/mouse-gamer',
  },
  {
    id: uuidv4(),
    title: 'Roteador Wi-Fi 6',
    description: 'Um roteador para conectar vários dispositivos à internet.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/roteador-wifi6',
  },
  {
    id: uuidv4(),
    title: 'SSD Externo',
    description: 'Um SSD para armazenar e transferir arquivos rapidamente.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/ssd-externo',
  },
  {
    id: uuidv4(),
    title: 'Alto-falantes Bluetooth',
    description: 'Alto-falantes sem fio para ouvir música com qualidade.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/alto-falantes-bluetooth',
  },
  {
    id: uuidv4(),
    title: 'Headset VR',
    description: 'Um headset para experimentar a realidade virtual.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/headset-vr',
  },
  {
    id: uuidv4(),
    title: 'Drone com Câmera',
    description: 'Um drone para capturar fotos e vídeos aéreos.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/drone-camera',
  },
  {
    id: uuidv4(),
    title: 'Projetor Portátil',
    description: 'Um projetor para assistir filmes e apresentações em qualquer lugar.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/projetor-portatil',
  },
  {
    id: uuidv4(),
    title: 'Carregador Sem Fio',
    description: 'Um carregador para carregar dispositivos sem fio.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/carregador-wireless',
  },
  {
    id: uuidv4(),
    title: 'Aspirador Robô',
    description: 'Um robô para limpar a casa automaticamente.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/aspirador-robo',
  },
  {
    id: uuidv4(),
    title: 'Cafeteira Inteligente',
    description: 'Uma cafeteira para preparar café com controle remoto.',
    image: 'https://via.placeholder.com/150',
    link: '/produto/cafeteira-inteligente',
  },
];